# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadSecureFile@1
    name: ghToken
    inputs:
      secureFile: 'mamalisz-gh-token'
    displayName: "Get gh token"

  - task: DownloadSecureFile@1
    name: gitToken
    inputs:
      secureFile: 'mamalisz_ssh_gh'
    displayName: "Get git token"

  - script: ./hello.sh $(ghToken.secureFilePath) $(gitToken.secureFilePath)
    displayName: 'Run a one-line script'
